# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
	minecraft_version=1.21.10
	loader_version=0.17.2
	fabric_version=0.136.0+1.21.10

# Mod Properties
	mod_version = 1.8+1.21.10
	maven_group = io.github.maheevil
	archives_base_name = some-ordinary-tweaks
	modmenu_version = 16.0.0-rc.1
	clothconfig_version = 20.0.149

